global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@voice-assistant.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://gateway:8080/alerts'
    send_resolved: true

- name: 'email-alerts'
  email_configs:
  - to: 'admin@voice-assistant.local'
    from: 'alerts@voice-assistant.local'
    smarthost: 'localhost:587'
    headers:
      Subject: 'Voice Assistant Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
